package com.bpm.minotaur.gamedata.monster.stitcher;

import com.badlogic.gdx.graphics.g3d.Model;
import com.badlogic.gdx.graphics.g3d.ModelInstance;
import com.badlogic.gdx.math.Matrix4;
import com.badlogic.gdx.utils.Disposable;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Runtime assembled creature: a torso ModelInstance plus a map of limb
 * ModelInstances keyed by socket name, plus procedurally generated bridge
 * geometry that fills the gaps between them.
 *
 * Limbs can be removed (severed) and the creature can be rotated as a unit
 * for multi-angle baking.
 *
 * Ownership: limb/torso ModelInstances do NOT own their backing Model (those
 * live in CreaturePartLibrary). Bridge Models ARE owned here and disposed on
 * dispose().
 */
public class StitchedCreature implements Disposable {

    /** Torso ModelInstance — may be null if no .g3db asset exists yet. */
    public final ModelInstance torso;

    /** Socket → limb ModelInstance. Ordered for deterministic rendering. */
    private final LinkedHashMap<String, ModelInstance> limbs;

    /** Procedural bridge geometry instances generated by GapBridgeBuilder. */
    private final List<ModelInstance> bridges = new ArrayList<>();

    /**
     * Backing Model objects for each bridge — owned by this creature and must
     * be explicitly disposed to free VRAM (GC will not do this).
     */
    private final List<Model> ownedBridgeModels = new ArrayList<>();

    // Base transforms captured at construction time so setFacing can compose
    // rotation on top of them instead of overwriting scale/translation.
    private final Matrix4 torsoBase;
    private final LinkedHashMap<String, Matrix4> limbBases;
    private final List<Matrix4> bridgeBases = new ArrayList<>();

    public StitchedCreature(ModelInstance torso, LinkedHashMap<String, ModelInstance> limbs) {
        this.torso = torso;
        this.limbs = limbs;
        this.torsoBase = torso != null ? torso.transform.cpy() : null;
        this.limbBases = new LinkedHashMap<>();
    }

    /** Call this after all limbs and bridges are added to freeze their base transforms. */
    public void freezeBases() {
        limbBases.clear();
        for (Map.Entry<String, ModelInstance> e : limbs.entrySet()) {
            limbBases.put(e.getKey(), e.getValue().transform.cpy());
        }
        bridgeBases.clear();
        for (ModelInstance b : bridges) {
            bridgeBases.add(b.transform.cpy());
        }
    }

    /** Convenience constructor for a single-part creature (e.g. an individual part bake). */
    public StitchedCreature(ModelInstance singlePart) {
        this.torso = singlePart;
        this.limbs = new LinkedHashMap<>();
        this.torsoBase = singlePart != null ? singlePart.transform.cpy() : null;
        this.limbBases = new LinkedHashMap<>();
    }

    // -------------------------------------------------------------------------
    // Bridge management
    // -------------------------------------------------------------------------

    /**
     * Registers a procedurally generated bridge between two anatomical joints.
     * The StitchedCreature takes ownership of {@code model} and will dispose it.
     *
     * @param model    The Model produced by GapBridgeBuilder.build() — owned here.
     * @param instance A ModelInstance wrapping that model, already positioned in world space.
     */
    public void addBridge(Model model, ModelInstance instance) {
        ownedBridgeModels.add(model);
        bridges.add(instance);
    }

    /** Unmodifiable view of bridge instances for rendering and ModelCache building. */
    public List<ModelInstance> getBridges() {
        return Collections.unmodifiableList(bridges);
    }

    // -------------------------------------------------------------------------
    // Limb access
    // -------------------------------------------------------------------------

    /** Unmodifiable view of the current limb map. */
    public Map<String, ModelInstance> getLimbs() {
        return Collections.unmodifiableMap(limbs);
    }

    public Set<String> getSockets() {
        return Collections.unmodifiableSet(limbs.keySet());
    }

    /** Returns the ModelInstance for a socket, or null if missing/severed. */
    public ModelInstance getLimb(String socket) {
        return limbs.get(socket);
    }

    /**
     * Removes a limb from the assembly and returns it (for use as a gore entity).
     * Returns null if the socket was already empty.
     */
    public ModelInstance removeLimb(String socket) {
        limbBases.remove(socket);
        return limbs.remove(socket);
    }

    // -------------------------------------------------------------------------
    // Facing rotation (used by CreatureBaker for N/E/S/W sprite capture)
    // -------------------------------------------------------------------------

    /**
     * Rotates the entire assembly around the Y axis for multi-angle baking.
     * Composes the rotation with each part's original base transform so that
     * pre-set scale and translation are preserved.
     */
    public void setFacing(float yDegrees) {
        Matrix4 rot = new Matrix4().setToRotation(com.badlogic.gdx.math.Vector3.Y, yDegrees);
        if (torso != null && torsoBase != null) {
            torso.transform.set(rot).mul(torsoBase);
        }
        for (Map.Entry<String, ModelInstance> e : limbs.entrySet()) {
            Matrix4 base = limbBases.get(e.getKey());
            if (base != null) {
                e.getValue().transform.set(rot).mul(base);
            }
        }
        for (int i = 0; i < bridges.size(); i++) {
            bridges.get(i).transform.set(rot).mul(bridgeBases.get(i));
        }
    }

    // -------------------------------------------------------------------------
    // Rendering
    // -------------------------------------------------------------------------

    /**
     * Renders all parts (torso, limbs, bridges) into a ModelBatch.
     * Null parts are skipped gracefully so partially-loaded assemblies work.
     */
    public void render(com.badlogic.gdx.graphics.g3d.ModelBatch batch,
                       com.badlogic.gdx.graphics.g3d.Environment env) {
        if (torso != null) batch.render(torso, env);
        for (ModelInstance limb : limbs.values()) {
            if (limb != null) batch.render(limb, env);
        }
        for (ModelInstance bridge : bridges) {
            batch.render(bridge, env);
        }
    }

    // -------------------------------------------------------------------------
    // Disposal
    // -------------------------------------------------------------------------

    /**
     * Disposes all procedurally generated bridge Models, freeing their VRAM.
     * Library-backed limb/torso Models are NOT disposed here — the library owns them.
     */
    @Override
    public void dispose() {
        for (Model m : ownedBridgeModels) {
            m.dispose();
        }
        ownedBridgeModels.clear();
        bridges.clear();
        bridgeBases.clear();
    }
}
