package com.bpm.minotaur.screens.inventory;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.files.FileHandle;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Persists inventory panel positions to {@code inventory_layout.txt} in the
 * game's working directory so you can fine-tune layout in debug mode without
 * recompiling.
 *
 * WORKFLOW
 *   1. Press F3 in-game to show the debug overlay.
 *   2. Drag any panel to its target position — labels update in real time.
 *   3. Click [SAVE LAYOUT] — writes inventory_layout.txt.
 *   4. The file has ready-to-paste setPosition() lines at the top.
 *      Copy them into ModernInventoryUI.java when you're happy.
 *   5. The key=x,y section at the bottom is re-read on next startup so
 *      positions persist across restarts during the tuning session.
 */
class InventoryLayoutConfig {

    // Keys — used as map keys and written to the layout file.
    static final String BACKPACK   = "backpack";
    static final String QUICKSLOTS = "quickSlots";
    static final String ATTRIBUTES = "attributes";
    static final String CORESTATS  = "coreStats";
    static final String SPELLBOOK  = "spellbook";
    static final String ALCHEMY    = "alchemy";

    private static final String FILE = "inventory_layout.txt";

    // Default positions — mirrors the hardcoded values in ModernInventoryUI.
    // Used when no saved layout file exists.
    private final Map<String, float[]> positions = new LinkedHashMap<>();

    InventoryLayoutConfig() {
        positions.put(BACKPACK,   new float[]{1040f, 497f});
        positions.put(QUICKSLOTS, new float[]{1036f, 371f});
        positions.put(ATTRIBUTES, new float[]{1040f,  20f});
        positions.put(CORESTATS,  new float[]{  20f,  20f});
        positions.put(SPELLBOOK,  new float[]{ 240f,  20f});
        positions.put(ALCHEMY,    new float[]{  20f, 220f});
        load();
    }

    float getX(String key) { return positions.get(key)[0]; }
    float getY(String key) { return positions.get(key)[1]; }

    void set(String key, float x, float y) {
        float[] p = positions.get(key);
        if (p != null) { p[0] = x; p[1] = y; }
    }

    // ── Persistence ───────────────────────────────────────────────────

    /**
     * Writes current positions to {@code inventory_layout.txt}.
     *
     * The file has two sections:
     *   • Ready-to-paste Java setPosition() calls (copy into ModernInventoryUI.java).
     *   • A key=x,y section that this class re-reads on the next startup.
     */
    void save() {
        StringBuilder sb = new StringBuilder();
        sb.append("# Inventory Panel Layout\n");
        sb.append("# Generated by debug overlay (F3 -> SAVE LAYOUT)\n");
        sb.append("# Paste the setPosition() lines below into ModernInventoryUI.java\n\n");

        for (Map.Entry<String, float[]> e : positions.entrySet()) {
            int x = (int) e.getValue()[0];
            int y = (int) e.getValue()[1];
            sb.append(e.getKey()).append(".setPosition(")
              .append(x).append("f, ").append(y).append("f);")
              .append("    // ").append(labelFor(e.getKey()))
              .append("\n");
        }

        sb.append("\n# key=x,y — read on startup to restore positions between runs\n");
        for (Map.Entry<String, float[]> e : positions.entrySet()) {
            sb.append(e.getKey()).append("=")
              .append((int) e.getValue()[0]).append(",")
              .append((int) e.getValue()[1]).append("\n");
        }

        try {
            FileHandle out = Gdx.files.local(FILE);
            out.writeString(sb.toString(), false);
            Gdx.app.log("InventoryLayout", "Saved -> " + out.file().getAbsolutePath());
        } catch (Exception ex) {
            Gdx.app.error("InventoryLayout", "Save failed", ex);
        }
    }

    // ── Private ───────────────────────────────────────────────────────

    private void load() {
        FileHandle f = Gdx.files.local(FILE);
        if (!f.exists()) return;
        for (String raw : f.readString().split("\n")) {
            String line = raw.trim();
            if (line.isEmpty() || line.startsWith("#")) continue;
            int eq = line.indexOf('=');
            if (eq < 0) continue;
            String key = line.substring(0, eq).trim();
            if (!positions.containsKey(key)) continue; // e.g. "foo.setPosition(..." lines → skipped
            String[] xy = line.substring(eq + 1).split(",");
            if (xy.length < 2) continue;
            try {
                positions.get(key)[0] = Float.parseFloat(xy[0].trim());
                positions.get(key)[1] = Float.parseFloat(xy[1].trim());
            } catch (NumberFormatException ignored) {}
        }
    }

    private static String labelFor(String key) {
        switch (key) {
            case BACKPACK:   return "BackpackPanel";
            case QUICKSLOTS: return "QuickSlotsPanel";
            case ATTRIBUTES: return "AttributesPanel";
            case CORESTATS:  return "CoreStatsPanel";
            case SPELLBOOK:  return "SpellbookPanel";
            case ALCHEMY:    return "AlchemyPanel";
            default:         return key;
        }
    }
}
